name:                pretty-gist
version:             0.0.0.1
github:              ChickenProp/pretty-gist
license:             BSD3
author:              Phil Hazelden
maintainer:          philip.hazelden@gmail.com
copyright:           2022 Phil Hazelden

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChickenProp/pretty-gist#readme>

default-extensions:
- DefaultSignatures
- DerivingStrategies
- FlexibleContexts
- LambdaCase
- OverloadedStrings
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter
- text

library:
  source-dirs: src

tests:
  pretty-gist-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pretty-gist
